// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDGiDDm1WkBMo7H8RextRwWQvIabzSO0',
    appId: '1:842647511765:web:a20a9785a7e8a502f5785c',
    messagingSenderId: '842647511765',
    projectId: 'sandhika-shop-7d4ae',
    authDomain: 'sandhika-shop-7d4ae.firebaseapp.com',
    storageBucket: 'sandhika-shop-7d4ae.appspot.com',
    measurementId: 'G-CZ15GMZE65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjT2usDkgGcbVlPo8aFa8vnKt-WqVs0c',
    appId: '1:842647511765:android:8bb27fb58a197ea4f5785c',
    messagingSenderId: '842647511765',
    projectId: 'sandhika-shop-7d4ae',
    storageBucket: 'sandhika-shop-7d4ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvQ1v5aee2zZgC9lcVmH9pg4JzdCTLGY',
    appId: '1:842647511765:ios:e615e420a1b22aa3f5785c',
    messagingSenderId: '842647511765',
    projectId: 'sandhika-shop-7d4ae',
    storageBucket: 'sandhika-shop-7d4ae.appspot.com',
    iosBundleId: 'com.example.tugasBesar1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdvQ1v5aee2zZgC9lcVmH9pg4JzdCTLGY',
    appId: '1:842647511765:ios:99eba6be8856f4b8f5785c',
    messagingSenderId: '842647511765',
    projectId: 'sandhika-shop-7d4ae',
    storageBucket: 'sandhika-shop-7d4ae.appspot.com',
    iosBundleId: 'com.example.tugasBesar1.RunnerTests',
  );
}
